# config.yaml

# Folders to watch/ingest (can be a list)
folders:
  - ~/Desktop/Crochet_patterns

# File extensions to skip (lowercase, with leading dot)
skip_exts:
  - .exe
  - .dll
  - .bin
  - .msi
  - .app
  - .com
  - .scr
  - .o
  - .so

# Chroma DB config
chroma_db_path: chroma_data

# SQLite queue path
queue_db: ingest_queue.sqlite3

# Embedding server/model config
embedding_url: http://localhost:11434/api/embeddings
embedding_model: llama3


# Number of search results (context passages) to send to LLM for answers
n_results: 5

# Worker batching (advanced: for parallel/cluster runs)
partition: 0        # worker number
total_partitions: 1 # total workers (set in Docker/env for parallelism)

# Logging
log_level: INFO
